// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillTrackerApi.Data;

#nullable disable

namespace SkillTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603003304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillTrackerApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 6, 3, 0, 33, 3, 559, DateTimeKind.Utc).AddTicks(850),
                            Level = 4,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 6, 3, 0, 33, 3, 559, DateTimeKind.Utc).AddTicks(860),
                            Level = 3,
                            Name = "React"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 6, 3, 0, 33, 3, 559, DateTimeKind.Utc).AddTicks(860),
                            Level = 4,
                            Name = "SQL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
